// <auto-generated />
using System;
using ASM_WebBanNuocUong.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASM_WebBanNuocUong.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202111333_Database")]
    partial class Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.ChiTietCombo", b =>
                {
                    b.Property<Guid>("MaChiTietCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComboMaCombo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaCombo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SanPhamMaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaChiTietCombo");

                    b.HasIndex("ComboMaCombo");

                    b.HasIndex("SanPhamMaSanPham");

                    b.ToTable("ComboDetails", (string)null);
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.ChiTietDonHang", b =>
                {
                    b.Property<Guid>("MaChiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonHangMaDonHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MaDonHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SanPhamMaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietDonHang");

                    b.HasIndex("DonHangMaDonHang");

                    b.HasIndex("SanPhamMaSanPham");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.Combo", b =>
                {
                    b.Property<Guid>("MaCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCombo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCombo");

                    b.ToTable("Combos", (string)null);
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.DanhMuc", b =>
                {
                    b.Property<Guid>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.DonHang", b =>
                {
                    b.Property<Guid>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiDungMaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.SanPham", b =>
                {
                    b.Property<Guid>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DanhMucMaDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MaDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSanPham");

                    b.HasIndex("DanhMucMaDanhMuc");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.ChiTietCombo", b =>
                {
                    b.HasOne("ASM_WebBanNuocUong.Models.Combo", "Combo")
                        .WithMany("DanhSachChiTietCombo")
                        .HasForeignKey("ComboMaCombo");

                    b.HasOne("ASM_WebBanNuocUong.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamMaSanPham");

                    b.Navigation("Combo");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("ASM_WebBanNuocUong.Models.DonHang", "DonHang")
                        .WithMany("DanhSachChiTiet")
                        .HasForeignKey("DonHangMaDonHang");

                    b.HasOne("ASM_WebBanNuocUong.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamMaSanPham");

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.DonHang", b =>
                {
                    b.HasOne("ASM_WebBanNuocUong.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.SanPham", b =>
                {
                    b.HasOne("ASM_WebBanNuocUong.Models.DanhMuc", "DanhMuc")
                        .WithMany("DanhSachSanPham")
                        .HasForeignKey("DanhMucMaDanhMuc");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.Combo", b =>
                {
                    b.Navigation("DanhSachChiTietCombo");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.DanhMuc", b =>
                {
                    b.Navigation("DanhSachSanPham");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.DonHang", b =>
                {
                    b.Navigation("DanhSachChiTiet");
                });
#pragma warning restore 612, 618
        }
    }
}
