// <auto-generated />
using System;
using ASM_WebBanNuocUong.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASM_WebBanNuocUong.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.ChiTietCombo", b =>
                {
                    b.Property<Guid>("MaChiTietCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaCombo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietCombo");

                    b.HasIndex("MaCombo");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ComboDetails", (string)null);

                    b.HasData(
                        new
                        {
                            MaChiTietCombo = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            MaCombo = new Guid("88888888-8888-8888-8888-888888888888"),
                            MaSanPham = new Guid("44444444-4444-4444-4444-444444444444"),
                            SoLuong = 1
                        },
                        new
                        {
                            MaChiTietCombo = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            MaCombo = new Guid("88888888-8888-8888-8888-888888888888"),
                            MaSanPham = new Guid("66666666-6666-6666-6666-666666666666"),
                            SoLuong = 1
                        },
                        new
                        {
                            MaChiTietCombo = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            MaCombo = new Guid("99999999-9999-9999-9999-999999999999"),
                            MaSanPham = new Guid("55555555-5555-5555-5555-555555555555"),
                            SoLuong = 2
                        });
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.ChiTietDonHang", b =>
                {
                    b.Property<Guid>("MaChiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("MaCombo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaDonHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietDonHang");

                    b.HasIndex("MaCombo");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("OrderDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietDonHang_LoaiSanPham", "(LoaiSanPham = 'SanPham' AND MaSanPham IS NOT NULL) OR (LoaiSanPham = 'Combo' AND MaCombo IS NOT NULL)");

                            t.HasCheckConstraint("CK_ChiTietDonHang_SanPhamOrCombo", "([MaSanPham] IS NOT NULL AND [MaCombo] IS NULL) OR ([MaSanPham] IS NULL AND [MaCombo] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.Combo", b =>
                {
                    b.Property<Guid>("MaCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenCombo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaCombo");

                    b.HasIndex("TenCombo")
                        .IsUnique();

                    b.ToTable("Combos", (string)null);

                    b.HasData(
                        new
                        {
                            MaCombo = new Guid("88888888-8888-8888-8888-888888888888"),
                            Gia = 60000m,
                            HinhAnh = "combo_sang.jpg",
                            MoTa = "Combo hoàn hảo cho buổi sáng",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenCombo = "Combo Sáng Đầy Năng Lượng",
                            TrangThai = true
                        },
                        new
                        {
                            MaCombo = new Guid("99999999-9999-9999-9999-999999999999"),
                            Gia = 80000m,
                            HinhAnh = "combo_chieu.jpg",
                            MoTa = "Combo thư giãn buổi chiều",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenCombo = "Combo Chiều Thư Giãn",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.DanhMuc", b =>
                {
                    b.Property<Guid>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("TenDanhMuc")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            MaDanhMuc = new Guid("11111111-1111-1111-1111-111111111111"),
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDanhMuc = "Cà phê",
                            TrangThai = true
                        },
                        new
                        {
                            MaDanhMuc = new Guid("22222222-2222-2222-2222-222222222222"),
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDanhMuc = "Trà sữa",
                            TrangThai = true
                        },
                        new
                        {
                            MaDanhMuc = new Guid("33333333-3333-3333-3333-333333333333"),
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDanhMuc = "Nước ép",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.DonHang", b =>
                {
                    b.Property<Guid>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ xác nhận");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Customer");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            MaNguoiDung = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            DiaChi = "123 Đường ABC, Quận 1, TP.HCM",
                            Email = "admin@nuocuong.com",
                            HoTen = "Admin Quản Trị",
                            MatKhau = "admin123",
                            NgaySinh = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789",
                            TrangThai = true,
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaNguoiDung = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            DiaChi = "456 Đường XYZ, Quận 2, TP.HCM",
                            Email = "customer@example.com",
                            HoTen = "Khách Hàng Mẫu",
                            MatKhau = "customer123",
                            NgaySinh = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0987654321",
                            TrangThai = true,
                            VaiTro = "Customer"
                        });
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.SanPham", b =>
                {
                    b.Property<Guid>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChuDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MaDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("TenSanPham")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            MaSanPham = new Guid("44444444-4444-4444-4444-444444444444"),
                            ChuDe = "Cà phê",
                            Gia = 25000m,
                            HinhAnh = "caphe_den.jpg",
                            MaDanhMuc = new Guid("11111111-1111-1111-1111-111111111111"),
                            MoTa = "Cà phê đen nguyên chất",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuongTon = 100,
                            TenSanPham = "Cà phê đen",
                            TrangThai = true
                        },
                        new
                        {
                            MaSanPham = new Guid("55555555-5555-5555-5555-555555555555"),
                            ChuDe = "Cà phê",
                            Gia = 30000m,
                            HinhAnh = "caphe_sua.jpg",
                            MaDanhMuc = new Guid("11111111-1111-1111-1111-111111111111"),
                            MoTa = "Cà phê sữa thơm ngon",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuongTon = 80,
                            TenSanPham = "Cà phê sữa",
                            TrangThai = true
                        },
                        new
                        {
                            MaSanPham = new Guid("66666666-6666-6666-6666-666666666666"),
                            ChuDe = "Trà sữa",
                            Gia = 35000m,
                            HinhAnh = "tra_sua_tran_chau.jpg",
                            MaDanhMuc = new Guid("22222222-2222-2222-2222-222222222222"),
                            MoTa = "Trà sữa thượng hạng",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuongTon = 120,
                            TenSanPham = "Trà sữa trân châu",
                            TrangThai = true
                        },
                        new
                        {
                            MaSanPham = new Guid("77777777-7777-7777-7777-777777777777"),
                            ChuDe = "Nước ép",
                            Gia = 40000m,
                            HinhAnh = "nuoc_ep_cam.jpg",
                            MaDanhMuc = new Guid("33333333-3333-3333-3333-333333333333"),
                            MoTa = "Nước ép cam tươi nguyên chất",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuongTon = 60,
                            TenSanPham = "Nước ép cam",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.ChiTietCombo", b =>
                {
                    b.HasOne("ASM_WebBanNuocUong.Models.Combo", "Combo")
                        .WithMany("DanhSachChiTietCombo")
                        .HasForeignKey("MaCombo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASM_WebBanNuocUong.Models.SanPham", "SanPham")
                        .WithMany("DanhSachChiTietCombo")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("ASM_WebBanNuocUong.Models.Combo", "Combo")
                        .WithMany("DanhSachChiTietDonHang")
                        .HasForeignKey("MaCombo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ASM_WebBanNuocUong.Models.DonHang", "DonHang")
                        .WithMany("DanhSachChiTiet")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASM_WebBanNuocUong.Models.SanPham", "SanPham")
                        .WithMany("DanhSachChiTietDonHang")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Combo");

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.DonHang", b =>
                {
                    b.HasOne("ASM_WebBanNuocUong.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachDonHang")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.SanPham", b =>
                {
                    b.HasOne("ASM_WebBanNuocUong.Models.DanhMuc", "DanhMuc")
                        .WithMany("DanhSachSanPham")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.Combo", b =>
                {
                    b.Navigation("DanhSachChiTietCombo");

                    b.Navigation("DanhSachChiTietDonHang");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.DanhMuc", b =>
                {
                    b.Navigation("DanhSachSanPham");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.DonHang", b =>
                {
                    b.Navigation("DanhSachChiTiet");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhSachDonHang");
                });

            modelBuilder.Entity("ASM_WebBanNuocUong.Models.SanPham", b =>
                {
                    b.Navigation("DanhSachChiTietCombo");

                    b.Navigation("DanhSachChiTietDonHang");
                });
#pragma warning restore 612, 618
        }
    }
}
